language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - DISTROOT=. BUILDROOT=../build ./scripts/build-json-fortran.sh
  - FC=gfortran-7 cmake -H$DISTROOT -B$BUILDROOT
  - cmake --build $BUILDROOT
script:
  - cd $BUILDROOT
  - ./bin/config
  - ctest
notifications:
email: false
after_success:
 - bash <(curl -s https://codecov.io/bash)
