language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - 
  - DISTROOT=$HOME/simsphere BUILDROOT=$HOME/simsphere-build ./scripts/build-json-fortran.sh
  - FC=gfortran-7 cmake .
  - cmake --build .
script:
  - ./bin/config
  - ctest
notifications:
email: false
after_success:
 - bash <(curl -s https://codecov.io/bash)
