language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-7
before_script:
  - ./scripts/build.sh
script:
  - ./bin/config
  - ctest
notifications:
email: false
after_success:
 - bash <(curl -s https://codecov.io/bash)
